force-app/main/default/objects/Case/fields/Causa__c.field-meta.xml
<CustomField>
    <fullName>Causa__c</fullName>
    <label>Causa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Comentario_de_Cierre__c.field-meta.xml
<CustomField>
    <fullName>Comentario_de_Cierre__c</fullName>
    <label>Comentario de Cierre</label>
    <length>3000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Caso_Reclamacion_Cerrada.recordType-meta.xml
<RecordType>
    <fullName>Caso_Reclamacion_Cerrada</fullName>
    <active>true</active>
    <businessProcess>Caso Reclamación</businessProcess>
    <label>Caso Reclamación Cerrada</label>
</RecordType>

force-app/main/default/objects/Causa_Cierre_Reclamacion__mdt/Causa_Cierre_Reclamacion__mdt.object-meta.xml
<CustomObject>
    <label>Causa Cierre Reclamación</label>
    <pluralLabel>Causas Cierre Reclamación</pluralLabel>
</CustomObject>

force-app/main/default/objects/Causa_Cierre_Reclamacion__mdt/fields/Causa__c.field-meta.xml
<CustomField>
    <fullName>Causa__c</fullName>
    <label>Causa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Venta Correcta existe soporte</fullName>
                <default>true</default>
                <label>Venta Correcta existe soporte</label>
            </value>
            <value>
                <fullName>Venta comercial incorrecta</fullName>
            </value>
            <value>
                <fullName>Datos insuficientes</fullName>
            </value>
            <value>
                <fullName>No recepción documentación</fullName>
            </value>
            <value>
                <fullName>Potencia correcta</fullName>
            </value>
            <value>
                <fullName>Error del Sistema</fullName>
            </value>
            <value>
                <fullName>Cierre criterio distribuidora</fullName>
            </value>
            <value>
                <fullName>La devolución se efectuó correctamente</fullName>
            </value>
            <value>
                <fullName>No procede devolver</fullName>
            </value>
            <value>
                <fullName>Se devuelve fianza</fullName>
            </value>
            <value>
                <fullName>Actuación Correcta</fullName>
            </value>
            <value>
                <fullName>Acuerdo de Pago previo erróneo</fullName>
            </value>
            <value>
                <fullName>Acuerdo previo realizo correctamente</fullName>
            </value>
            <value>
                <fullName>Acumulación facturas tras 60 días</fullName>
            </value>
            <value>
                <fullName>Alta correcta</fullName>
            </value>
            <value>
                <fullName>Alta errónea</fullName>
            </value>
            <value>
                <fullName>Anulación en curso o rechazada</fullName>
            </value>
            <value>
                <fullName>Aplic.deuda de entreg.a cuenta</fullName>
            </value>
            <value>
                <fullName>Aplicación Cobro</fullName>
            </value>
            <value>
                <fullName>Atención Incorrecta</fullName>
            </value>
            <value>
                <fullName>Baja correcta</fullName>
            </value>
            <value>
                <fullName>Baja diferida errónea</fullName>
            </value>
            <value>
                <fullName>Baja en contrato erróneo</fullName>
            </value>
            <value>
                <fullName>Baja por cambio titular erróneo</fullName>
            </value>
            <value>
                <fullName>Baja por impago no procedente</fullName>
            </value>
            <value>
                <fullName>Cambio de email</fullName>
            </value>
            <value>
                <fullName>Cliente no colabora</fullName>
            </value>
            <value>
                <fullName>Cliente no localizado</fullName>
            </value>
            <value>
                <fullName>Cobro registrado correctamente</fullName>
            </value>
            <value>
                <fullName>Cobro ya realizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resultado_Cierre_Reclamacion__mdt/Resultado_Cierre_Reclamacion__mdt.object-meta.xml
<CustomObject>
    <label>Resultado Cierre Reclamación</label>
    <pluralLabel>Resultado Cierre Reclamación</pluralLabel>
</CustomObject>

force-app/main/default/objects/Resultado_Cierre_Reclamacion__mdt/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Improcedente</fullName>
                <default>true</default>
                <label>Improcedente</label>
            </value>
            <value>
                <fullName>Procedente</fullName>
            </value>
            <value>
                <fullName>Anulada</fullName>
            </value>
            <value>
                <fullName>No gestionable</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TFG_Close_Claim.cls
/*
  * @ComponentName	  TFG_CreateAccount
  * @description	  Component to create a new Account
  * @author			  FJMG
  * @email			  fran19943@gmail.com
  * @version		  V0.1
  * @dateCreated	  2023/06/18
  * @lastChange		
*/

public with sharing class TFG_Close_Claim {
	
	public class Result {
        @AuraEnabled
        public String value { get; set; }
    }

    @AuraEnabled
    public static Map<String, List<Result>> getCauseAndResults(String recordId) {
        Map<String, List<Result>> results = new Map<String, List<Result>>();
        List<Result> listCausa = new List<Result>();
        List<Result> listResultado = new List<Result>();

        if (Schema.sObjectType.Case.isAccessible() &&
            Schema.sObjectType.Causa_Cierre_Reclamacion__mdt.isAccessible() &&
            Schema.sObjectType.Resultado_Cierre_Reclamacion__mdt.isAccessible()) {

            List<Causa_Cierre_Reclamacion__mdt> causaPicklistValues = [SELECT Causa__c FROM Causa_Cierre_Reclamacion__mdt];
            for (Causa_Cierre_Reclamacion__mdt causa : causaPicklistValues) {
                Result item = new Result();
                item.value = causa.Causa__c;
                listCausa.add(item);
            }

            List<Resultado_Cierre_Reclamacion__mdt> resultadoPicklistValues = [SELECT Resultado__c FROM Resultado_Cierre_Reclamacion__mdt];
            for (Resultado_Cierre_Reclamacion__mdt resultado : resultadoPicklistValues) {
                Result item = new Result();
                item.value = resultado.Resultado__c;
                listResultado.add(item);
            }
            results.put('listCausa', listCausa);
            results.put('listResultado', listResultado);
        }
        return results;
    }
    
	@AuraEnabled
	public static String closeSaveClaim(String selectedCause, String selectedResult, String comments, String recordId){
        String res = '';
        Id rTypeClose = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Caso_Reclamacion_Cerrada').getRecordTypeId();
        String userId = UserInfo.getUserId();
        // Get the User record of the currently logged-in user
        User currentUser = [SELECT ProfileId FROM User WHERE Id = :userId LIMIT 1];

        // Get the Profile record using the ProfileId from the User record
        Profile userProfile = [SELECT Id, Name FROM Profile WHERE Id = :currentUser.ProfileId LIMIT 1];
        String profileName = userProfile.Name;

        Case caseObj = [SELECT Id, Resultado__c, Causa__c, Status, OwnerId, Comentario_de_Cierre__c FROM Case WHERE Id =: recordId];

        if(profileName == 'System Administrator') {
            caseObj.Resultado__c = selectedResult;
            caseObj.Causa__c = selectedResult;
            caseObj.Comentario_de_Cierre__c = comments;
            caseObj.Status = 'Resuelta';
            caseObj.RecordTypeId = rTypeClose;
            update caseObj;
            res = 'OK';
        }
        else if(caseObj.OwnerId != userId) {
            res = 'KO';
        }
        else {
            caseObj.Resultado__c = selectedResult;
            caseObj.Causa__c = selectedResult;
            caseObj.Comentario_de_Cierre__c = comments;
            caseObj.Status = 'Resuelta';
            caseObj.RecordTypeId = rTypeClose;
            update caseObj;
            res = 'OK';
        }
        return res;
	}
}