force-app/main/default/objects/Case/fields/Causa__c.field-meta.xml
<CustomField>
    <fullName>Causa__c</fullName>
    <label>Causa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Resultado__c.field-meta.xml
<CustomField>
    <fullName>Resultado__c</fullName>
    <label>Resultado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Caso_Reclamacion_Abierta.recordType-meta.xml
<RecordType>
    <fullName>Caso_Reclamacion_Abierta</fullName>
    <active>true</active>
    <businessProcess>Caso Reclamación</businessProcess>
    <label>Caso Reclamación Abierta</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Caso_Reclamacion_Cerrada.recordType-meta.xml
<RecordType>
    <fullName>Caso_Reclamacion_Cerrada</fullName>
    <active>true</active>
    <businessProcess>Caso Reclamación</businessProcess>
    <label>Caso Reclamación Cerrada</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <label>Apellidos</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Metodo_contacto__c.field-meta.xml
<CustomField>
    <fullName>Metodo_contacto__c</fullName>
    <description>Método de contacto del contacto</description>
    <label>Método de contacto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Teléfono</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NIF__c.field-meta.xml
<CustomField>
    <fullName>NIF__c</fullName>
    <description>DNI/Identificador del contacto</description>
    <label>NIF</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <description>Nombre del contacto</description>
    <label>Nombre</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Titular del contrato</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <description>Teléfono de contacto</description>
    <label>Teléfono</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TFG_WhatsAppIntegrationControllerTest.cls
@isTest
public class TFG_WhatsAppIntegrationControllerTest {

    // Create a mock class for HTTP Callout
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Create a mock HTTPResponse
            HttpResponse res = new HttpResponse();
            res.setStatus('OK');
            res.setStatusCode(200);
            return res;
        }
    }

    @isTest
    static void testSendMessageClaimCreated() {
        // Crear un registro de prueba de Contacto
        Contact contactTest = new Contact(
            Nombre__c = 'Fran',
            Apellidos__c = 'Marqués',
            NIF__c = '75729302P',
            Metodo_contacto__c = 'Teléfono',
            Rol__c = 'Titular del contrato',
            FirstName = 'Fran',
            LastName = 'Prueba',
            Telefono__c = '671481834' // Número de teléfono válido
        );
        insert contactTest;

        // Crear un registro de prueba de Case relacionado con el Contacto
        Id recordTypeClaimCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Caso_Reclamacion_Abierta').getRecordTypeId();
        Case caseTest = new Case(
            ContactId = contactTest.Id,
            Status = 'Recibida', // Estado válido para el mensaje de prueba
            RecordTypeId = recordTypeClaimCase // Asigna el Record Type correcto
        );
        insert caseTest;

        // Set up the mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        // Llamar al método de la clase principal que deseas probar
        TFG_WhatsAppIntegrationController.sendMessageClaimCreated(new List<Id>{caseTest.Id});
        Test.stopTest();
    }

    @isTest
    static void testSendMessageClaimUpdated() {
        // Crear un registro de prueba de Contacto
        Contact contactTest = new Contact(
            Nombre__c = 'Fran',
            Apellidos__c = 'Marqués',
            NIF__c = '75729302P',
            Metodo_contacto__c = 'Teléfono',
            Rol__c = 'Titular del contrato',
            FirstName = 'Fran',
            LastName = 'Prueba',
            Telefono__c = '671481834' // Número de teléfono válido
        );
        insert contactTest;

        // Crear registros de prueba de Case relacionado con el Contacto
        Id recordTypeClaimCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Caso_Reclamacion_Abierta').getRecordTypeId();
        Id recordTypeClaimCaseClose = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Caso_Reclamacion_Cerrada').getRecordTypeId();
        Case case1 = new Case(
            ContactId = contactTest.Id,
            Status = 'Resolviendo', // Estado válido para el mensaje de prueba
            RecordTypeId = recordTypeClaimCase // Asigna el Record Type correcto
        );
        insert case1;

        Case case2 = new Case(
            ContactId = contactTest.Id,
            Causa__c = 'Procedente',
            Resultado__c = 'Procedente',
            Status = 'Resuelta', // Estado válido para el mensaje de prueba
            RecordTypeId = recordTypeClaimCaseClose // Asigna el Record Type correcto
        );
        insert case2;

        // Set up the mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        // Llamar al método de la clase principal que deseas probar
        TFG_WhatsAppIntegrationController.sendMessageClaimUpdated(new List<Id>{case1.Id});
        TFG_WhatsAppIntegrationController.sendMessageClaimUpdated(new List<Id>{case2.Id});
        Test.stopTest();
    }

    @isTest
    static void testSendMessageClaimUpdatedNull() {
        // Crear un registro de prueba de Contacto
        Contact contactTest = new Contact(
            Nombre__c = 'Fran',
            Apellidos__c = 'Marqués',
            NIF__c = '75729302P',
            Metodo_contacto__c = 'Teléfono',
            Rol__c = 'Titular del contrato',
            FirstName = 'Fran',
            LastName = 'Prueba',
            Telefono__c = null // Número de teléfono válido
        );
        insert contactTest;

        // Crear registro de prueba de Case relacionado con el Contacto (Teléfono null)
        Id recordTypeClaimCase = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('Caso_Reclamacion_Abierta').getRecordTypeId();
        Case caseInsert = new Case(
            ContactId = contactTest.Id,
            Status = 'Resolviendo', // Estado válido para el mensaje de prueba
            RecordTypeId = recordTypeClaimCase // Asigna el Record Type correcto
        );
        insert caseInsert;

        // Set up the mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        // Llamar al método de la clase principal que deseas probar
        TFG_WhatsAppIntegrationController.sendMessageClaimUpdated(new List<Id>{caseInsert.Id});
        Test.stopTest();
    }
}