force-app/main/default/objects/Subtipo_reclamacion__mdt/Subtipo_reclamacion__mdt.object-meta.xml
<CustomObject>
    <label>Subtipo Reclamación</label>
    <pluralLabel>Subtipo Reclamación</pluralLabel>
</CustomObject>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Clase__c.field-meta.xml
<CustomField>
    <fullName>Clase__c</fullName>
    <label>Clase</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Descripcion_Subtipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Subtipo_Reclamacion__c</fullName>
    <label>Descripción Subtipo Reclamación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Mensajeria_Subtipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Mensajeria_Subtipo_Reclamacion__c</fullName>
    <label>Mensajería Subtipo Reclamación</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Tipo_Reclamacion__mdt/Tipo_Reclamacion__mdt.object-meta.xml
<CustomObject>
    <label>Tipo Reclamación</label>
    <pluralLabel>Tipo Reclamación</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tipo_Reclamacion__mdt/fields/Descripcion_Tipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Tipo_Reclamacion__c</fullName>
    <label>Descripción Tipo Reclamación</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tipo_Reclamacion__mdt/fields/Mensajeria_Tipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Mensajeria_Tipo_Reclamacion__c</fullName>
    <label>Mensajería Tipo Reclamación</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TFG_ClaimClassifierTest.cls
@isTest
private class TFG_ClaimClassifierTest {
    
    @isTest
    static void testGetTypesAndSubTypes() {
        // Preparar datos de prueba
        List<Tipo_Reclamacion__mdt> tipoReclamacion = new List<Tipo_Reclamacion__mdt>();
        tipoReclamacion = [SELECT DeveloperName, Descripcion_Tipo_Reclamacion__c, Mensajeria_Tipo_Reclamacion__c
                           FROM Tipo_Reclamacion__mdt
                           WHERE Activo__c = TRUE ORDER BY Descripcion_Tipo_Reclamacion__c ASC LIMIT 1];

        List<Subtipo_Reclamacion__mdt> subtipoReclamacion = new List<Subtipo_Reclamacion__mdt>();
        subtipoReclamacion = [SELECT Descripcion_Subtipo_Reclamacion__c, Mensajeria_Subtipo_Reclamacion__c, DeveloperName, Clase__c
                              FROM	Subtipo_Reclamacion__mdt
                              WHERE	Activo__c = TRUE LIMIT 1];
        
        // Llamar al método de prueba
        Test.startTest();
        Map<String, Object> results = TFG_ClaimClassifier.getTypesAndSubTypes();
        Test.stopTest();
        
        // Verificar el resultado
        Map<String, String> customerTypeMgsByType = (Map<String, String>)results.get('customerTypeMgsByType');
        Map<String, Map<String, String>> customerSubTypeAndMsgByTypeDesc = (Map<String, Map<String, String>>)results.get('customerSubTypeAndMsgByTypeDesc');
        Map<String, String> codeAndCustomerType = (Map<String, String>)results.get('codeAndCustomerType');
        Map<String, String> codeAndCustomerSubType = (Map<String, String>)results.get('codeAndCustomerSubType');
        Map<String, String> classAndCustomerSubType = (Map<String, String>)results.get('classAndCustomerSubType');
        
        System.assertNotEquals(null, customerTypeMgsByType);
        System.assertNotEquals(null, customerSubTypeAndMsgByTypeDesc);
        System.assertNotEquals(null, codeAndCustomerType);
        System.assertNotEquals(null, codeAndCustomerSubType);
        System.assertNotEquals(null, classAndCustomerSubType);
    }
}