force-app/main/default/objects/Subtipo_reclamacion__mdt/Subtipo_reclamacion__mdt.object-meta.xml
<CustomObject>
    <label>Subtipo Reclamación</label>
    <pluralLabel>Subtipo Reclamación</pluralLabel>
</CustomObject>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Activo__c.field-meta.xml
<CustomField>
    <fullName>Activo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Activo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Clase__c.field-meta.xml
<CustomField>
    <fullName>Clase__c</fullName>
    <label>Clase</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Descripcion_Subtipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Subtipo_Reclamacion__c</fullName>
    <label>Descripción Subtipo Reclamación</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Mensajeria_Subtipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Mensajeria_Subtipo_Reclamacion__c</fullName>
    <label>Mensajería Subtipo Reclamación</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subtipo_reclamacion__mdt/fields/Tipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Reclamacion__c</fullName>
    <label>Tipo Reclamación</label>
    <referenceTo>Tipo_Reclamacion__mdt</referenceTo>
    <relationshipLabel>Subtipo Reclamación</relationshipLabel>
    <relationshipName>Subtipo_Reclamacion</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Tipo_Reclamacion__mdt/Tipo_Reclamacion__mdt.object-meta.xml
<CustomObject>
    <label>Tipo Reclamación</label>
    <pluralLabel>Tipo Reclamación</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tipo_Reclamacion__mdt/fields/Descripcion_Tipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Descripcion_Tipo_Reclamacion__c</fullName>
    <label>Descripción Tipo Reclamación</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tipo_Reclamacion__mdt/fields/Mensajeria_Tipo_Reclamacion__c.field-meta.xml
<CustomField>
    <fullName>Mensajeria_Tipo_Reclamacion__c</fullName>
    <label>Mensajería Tipo Reclamación</label>
    <length>300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TFG_ClaimClassifier.cls
/*
  * @ComponentName	TFG_ClaimClassifier
  * @description	Controller component from step2 in the claim classifier
  * @author			FJMG
  * @email			fran19943@gmail.com
  * @version		V0.1
  * @dateCreated	2023/06/10
  * @lastChange		
*/

public with sharing class TFG_ClaimClassifier {
    
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getTypesAndSubTypes() {
        Map<String, Object> results = new Map<String, Object>();
        Map<String, String> customerTypeMgsByType = new Map<String, String>();
        Map<String, Map<String, String>> customerSubTypeAndMsgByTypeDesc = new Map<String, Map<String, String>>();
        Map<String, String> codeAndCustomerType = new Map<String,String>();
        Map<String, String> codeAndCustomerSubType = new Map<String,String>();
        Map<String, String> classAndCustomerSubType = new Map<String,String>();

        List<Tipo_Reclamacion__mdt> customerTypes = new List<Tipo_Reclamacion__mdt>();
        if(Schema.sObjectType.Tipo_Reclamacion__mdt.isAccessible()){
            customerTypes = [SELECT
                            DeveloperName,
                            Descripcion_Tipo_Reclamacion__c,
                            Mensajeria_Tipo_Reclamacion__c,
                                (SELECT Descripcion_Subtipo_Reclamacion__c, 
                                Mensajeria_Subtipo_Reclamacion__c,
                                DeveloperName,
                                Clase__c
                                FROM	Subtipo_Reclamacion__r
                                WHERE	Activo__c = TRUE)
                            FROM Tipo_Reclamacion__mdt
                            WHERE Activo__c = TRUE ORDER BY Descripcion_Tipo_Reclamacion__c ASC]; 
        }
        
        for (Tipo_Reclamacion__mdt customerType : customerTypes) {
            Map<String, String> subTypes = new Map<String, String>(); 
            for (Subtipo_Reclamacion__mdt subType : customerType.Subtipo_Reclamacion__r) {
                subTypes.put(subType.Descripcion_Subtipo_Reclamacion__c , subType.Mensajeria_Subtipo_Reclamacion__c);
                codeAndCustomerSubType.put(subType.Descripcion_Subtipo_Reclamacion__c, subType.DeveloperName);
                classAndCustomerSubType.put(subType.Descripcion_Subtipo_Reclamacion__c, subType.Clase__c);       
            }
            customerTypeMgsByType.put(customerType.Descripcion_Tipo_Reclamacion__c, customerType.Mensajeria_Tipo_Reclamacion__c);
            customerSubTypeAndMsgByTypeDesc.put(customerType.Descripcion_Tipo_Reclamacion__c, subTypes);
            codeAndCustomerType.put(customerType.Descripcion_Tipo_Reclamacion__c,customerType.DeveloperName);
        }
        
        results.put('customerTypeMgsByType', customerTypeMgsByType);
        results.put('customerSubTypeAndMsgByTypeDesc', customerSubTypeAndMsgByTypeDesc); 
        results.put('codeAndCustomerType', codeAndCustomerType);
        results.put('codeAndCustomerSubType', codeAndCustomerSubType); 
        results.put('classAndCustomerSubType', classAndCustomerSubType);      
        
        return results;
    }
}