force-app/main/default/objects/Account/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <formula>ContactoTitular__r.Apellidos__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Apellidos</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ContactoTitular__c.field-meta.xml
<CustomField>
    <fullName>ContactoTitular__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto Titular</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <formula>ContactoTitular__r.Nombre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <label>Apellidos</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <description>Nombre del contacto</description>
    <label>Nombre</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Titular del contrato</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TFG_CreateContact.cls
/*
  * @ComponentName	TFG_CreateContact
  * @description	Component to create a new Contact
  * @author			FJMG
  * @email			fran19943@gmail.com
  * @version		V0.1
  * @dateCreated	2023/05/13
  * @lastChange		
*/

public with sharing class TFG_CreateContact {
    @AuraEnabled
    public static Id createContact(Contact contactInserted) {
        Contact newContact = new Contact();
        Contact contactoTitular = null;
        newContact = contactInserted;
        newContact.Nombre__c = newContact.FirstName;
        newContact.Apellidos__c = newContact.LastName;
        Account acc = [SELECT id, Name, ContactoTitular__c FROM Account WHERE Id =:newContact.AccountId LIMIT 1].get(0);
        if(acc.ContactoTitular__c != null) {
          contactoTitular = [SELECT id, Rol__c FROM Contact WHERE id =: acc.ContactoTitular__c LIMIT 1].get(0);
        }
        insert newContact;

        if(newContact.Rol__c == 'Titular del contrato') {
          if(contactoTitular != null) {
            contactoTitular.Rol__c = 'Autorizado';
            acc.ContactoTitular__c = newContact.Id;
            acc.Name = newContact.Nombre__c + ' ' + newContact.Apellidos__c;
            update acc;
            update contactoTitular;
          }
          else {
            acc.ContactoTitular__c = newContact.Id;
            acc.Name = newContact.Nombre__c + ' ' + newContact.Apellidos__c;
            update acc;
          }
        }
        return newContact.Id;
    }
}