force-app/main/default/objects/Account/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <formula>ContactoTitular__r.Apellidos__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Apellidos</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <formula>ContactoTitular__r.Direccion__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dirección</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Metodo_contacto__c.field-meta.xml
<CustomField>
    <fullName>Metodo_contacto__c</fullName>
    <formula>TEXT(ContactoTitular__r.Metodo_contacto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Método de contacto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIF__c.field-meta.xml
<CustomField>
    <fullName>NIF__c</fullName>
    <formula>ContactoTitular__r.NIF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NIF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <formula>ContactoTitular__r.Nombre__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nombre</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <formula>ContactoTitular__r.Telefono__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Teléfono</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Apellidos__c.field-meta.xml
<CustomField>
    <fullName>Apellidos__c</fullName>
    <label>Apellidos</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Direccion__c.field-meta.xml
<CustomField>
    <fullName>Direccion__c</fullName>
    <description>Dirección del contacto</description>
    <label>Dirección</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Metodo_contacto__c.field-meta.xml
<CustomField>
    <fullName>Metodo_contacto__c</fullName>
    <description>Método de contacto del contacto</description>
    <label>Método de contacto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Teléfono</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NIF__c.field-meta.xml
<CustomField>
    <fullName>NIF__c</fullName>
    <description>DNI/Identificador del contacto</description>
    <label>NIF</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nombre__c.field-meta.xml
<CustomField>
    <fullName>Nombre__c</fullName>
    <description>Nombre del contacto</description>
    <label>Nombre</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Titular del contrato</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Telefono__c.field-meta.xml
<CustomField>
    <fullName>Telefono__c</fullName>
    <description>Teléfono de contacto</description>
    <label>Teléfono</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TFG_InitialClaimRegistrationTest.cls
@IsTest
private class TFG_InitialClaimRegistrationTest {
    @IsTest
    static void testGetInitialData() {
        // Crear una cuenta de ejemplo para obtener el Id
        Account testAccount = new Account();
        testAccount.Name = 'Test Initial';
        insert testAccount;
        
        // Crear contactos de ejemplo relacionados con la cuenta
        Contact contact1 = new Contact();
        contact1.FirstName = 'A';
        contact1.LastName = 'B';
        contact1.AccountId = testAccount.Id;
        contact1.NIF__c = '12345678A';
        contact1.Metodo_contacto__c = 'Email';
        contact1.Email = 'prueba@example.com';
        contact1.Telefono__c = '950220405';
        contact1.Rol__c = 'Titular del contrato';
        contact1.Direccion__c = 'Calle Falsa 123';
        contact1.Nombre__c = 'A';
        contact1.Apellidos__c = 'B';

        
        Contact contact2 = new Contact();
        contact2.FirstName = 'C';
        contact2.LastName = 'D';
        contact2.AccountId = testAccount.Id;
        contact2.NIF__c = '87654321A';
        contact2.Metodo_contacto__c = 'Teléfono';
        contact2.Email = 'prueba2@example.com';
        contact2.Telefono__c = '987654321';
        contact2.Rol__c = 'Autorizado';
        contact2.Direccion__c = '456 Elm St';
        contact2.Nombre__c = 'C';
        contact2.Apellidos__c = 'D';
        
        insert new List<Contact>{ contact1, contact2 };
        
        // Llamar al método getInitialData para obtener los datos iniciales
        Map<String, Object> initialData = TFG_InitialClaimRegistration.getInitialData(testAccount.Id);
        
        // Verificar los datos obtenidos
        List<Contact> contacts = (List<Contact>) initialData.get('contacts');
        System.assertEquals(2, contacts.size());
        
        Contact resultContact1 = contacts[0];
        System.assertEquals('A', resultContact1.FirstName);
        System.assertEquals('B', resultContact1.LastName);
        System.assertEquals('A', resultContact1.Nombre__c);
        System.assertEquals('B', resultContact1.Apellidos__c);
        System.assertEquals('12345678A', resultContact1.NIF__c);
        System.assertEquals('Email', resultContact1.Metodo_contacto__c);
        System.assertEquals('prueba@example.com', resultContact1.Email);
        System.assertEquals('950220405', resultContact1.Telefono__c);
        System.assertEquals('Titular del contrato', resultContact1.Rol__c);
        System.assertEquals('Calle Falsa 123', resultContact1.Direccion__c);
        
        Contact resultContact2 = contacts[1];
        System.assertEquals('C', resultContact2.FirstName);
        System.assertEquals('D', resultContact2.LastName);
        System.assertEquals('C', resultContact2.Nombre__c);
        System.assertEquals('D', resultContact2.Apellidos__c);
        System.assertEquals('87654321A', resultContact2.NIF__c);
        System.assertEquals('Teléfono', resultContact2.Metodo_contacto__c);
        System.assertEquals('prueba2@example.com', resultContact2.Email);
        System.assertEquals('987654321', resultContact2.Telefono__c);
        System.assertEquals('Autorizado', resultContact2.Rol__c);
        System.assertEquals('456 Elm St', resultContact2.Direccion__c);
    }
}