force-app/main/default/objects/Account/fields/ContactoTitular__c.field-meta.xml
<CustomField>
    <fullName>ContactoTitular__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contacto Titular</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Metodo_contacto__c.field-meta.xml
<CustomField>
    <fullName>Metodo_contacto__c</fullName>
    <formula>TEXT(ContactoTitular__r.Metodo_contacto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Método de contacto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/NIF__c.field-meta.xml
<CustomField>
    <fullName>NIF__c</fullName>
    <formula>ContactoTitular__r.NIF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NIF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Metodo_contacto__c.field-meta.xml
<CustomField>
    <fullName>Metodo_contacto__c</fullName>
    <description>Método de contacto del contacto</description>
    <label>Método de contacto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Teléfono</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/NIF__c.field-meta.xml
<CustomField>
    <fullName>NIF__c</fullName>
    <description>DNI/Identificador del contacto</description>
    <label>NIF</label>
    <length>9</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Rol__c.field-meta.xml
<CustomField>
    <fullName>Rol__c</fullName>
    <label>Rol</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Titular del contrato</fullName>
            </value>
            <value>
                <fullName>Autorizado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TFG_CreateContactTest.cls
@IsTest
private class TFG_CreateContactTest {
    @IsTest
    static void testCreateContact() {
        // Crear una cuenta de ejemplo para relacionar al contacto
        Account testAccount = new Account();
        testAccount.Name = 'Test Account';
        insert testAccount;
        
        // Crear un contacto de ejemplo para insertar
        Contact contactToInsert = new Contact();
        contactToInsert.FirstName = 'Test';
        contactToInsert.LastName = 'Fran';
        contactToInsert.AccountId = testAccount.Id;
        contactToInsert.Rol__c = 'Titular del contrato';
        contactToInsert.NIF__c = '75729302P';
        contactToInsert.Metodo_contacto__c = 'SMS';

        
        // Llamar al método de creación de contacto
        Id insertedContactId = TFG_CreateContact.createContact(contactToInsert);
        
        // Verificar que se haya insertado correctamente
        Contact insertedContact = [SELECT Id, FirstName, LastName, AccountId, Rol__c, NIF__c, Metodo_contacto__c FROM Contact WHERE Id = :insertedContactId];
        System.assertEquals('Test', insertedContact.FirstName);
        System.assertEquals('Fran', insertedContact.LastName);
        
        // Verificar que la cuenta y el contacto estén correctamente relacionados
        Account updatedAccount = [SELECT Id, Name, ContactoTitular__c FROM Account WHERE Id = :testAccount.Id];
        System.assertEquals(insertedContactId, updatedAccount.ContactoTitular__c);
        System.assertEquals('Test Fran', updatedAccount.Name);
    }
}